### ISSUE TITLE
Can not import file from package

### ISSUE THREAD

**Issue by AKHACKER-program4hack** [operatorequals/httpimport#34]
I have run that code but i have error in importing

this is my repo [link](https://github.com/AKHACKER-program4hack/searcher)

and this is my code

```
with httpimport.github_repo('AKHACKER-program4hack', 'searcher', branch='master'):
    import searcher.forsearch
    s = forsearch.Searcher()
    s.printuser()
```

And i am getting this error:

```
Traceback (most recent call last):
  File "/home/ak/Desktop/development/pythonwork/testing/httpimport/testing.py", line 8, in <module>
    s = forsearch.Searcher()
NameError: name 'forsearch' is not defined
```
Can anyone tell me what's the problem

**Comment by AKHACKER-program4hack** [comment]
> I have run that code but i have error in importing
> 
> this is my repo [link](https://github.com/AKHACKER-program4hack/searcher)
> 
> and this is my code
> 
> ```
> with httpimport.github_repo('AKHACKER-program4hack', 'searcher', branch='master'):
>     import searcher.forsearch
>     s = forsearch.Searcher()
>     s.printuser()
> ```
> 
> And i am getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/ak/Desktop/development/pythonwork/testing/httpimport/testing.py", line 8, in <module>
>     s = forsearch.Searcher()
> NameError: name 'forsearch' is not defined
> ```
> 
> Can anyone tell me what's the problem

@operatorequals

**Comment by AKHACKER-program4hack** [comment]
Sorry for disturbance but i have found the solution

i just need to use a keyword `as` in importing

```
with httpimport.github_repo('AKHACKER-program4hack', 'searcher', branch='master'):
    import searcher.forsearch as forsearch
    s = forsearch.Searcher()
    s.printuser()

```
